export const nameMapper = {
  'Gary Trent Jr.': 'Gary Trent',
  'Otto Porter Jr.': 'Otto Porter',
  'Craig Porter Jr.': 'Craig Porter',
  'Marvin Bagley III': 'Marvin Bagley',
  'Jaime Jaquez Jr.': 'Jaime Jaquez',
  'Jaren Jackson Jr.': 'Jaren Jackson',
  'Kenneth Lofton Jr.': 'Kenneth Lofton',
  'Vince Williams Jr.': 'Vince Williams',
  'Kelly Oubre Jr.': 'Kelly Oubre',
  'Marjon Beauchamp': 'MarJon Beauchamp',
  // 'Gary Payton II': 'Gary Payton',
  // 'Gary Payton': 'Gary Payton II',
  'Marcus Morris Sr.': 'Marcus Morris',
  'Andre Jackson Jr.': 'Andre Jackson',
  'TyTy Washington Jr.': 'TyTy Washington',
  // 'KJ Martin': 'Kenyon Martin',
  'Jabari Smith Jr.': 'Jabari Smith',
  'Troy Brown Jr.': 'Troy Brown',
  'Wendell Moore Jr.': 'Wendell Moore',
  'Larry Nance Jr.': 'Larry Nance',
  'Kira Lewis Jr.': 'Kira Lewis',
  'Patrick Baldwin Jr.': 'Patrick Baldwin',
  'Dereck Lively II': 'Dereck Lively',
  'Tim Hardaway Jr.': 'Tim Hardaway',
  'Derrick Jones Jr.': 'Derrick Jones',
  'Michael Porter Jr.': 'Michael Porter',
  'PJ Washington': 'P.J. Washington',
  'Nick Smith Jr.': 'Nick Smith',
  'Gregory Jackson': 'GG Jackson',
  'Wendell Carter Jr.': 'Wendell Carter',
  'Lonnie Walker IV': 'Lonnie Walker',
  'Dennis Smith Jr.': 'Dennis Smith',
  'Harry Giles III': 'Harry Giles',
  'Ron Harper Jr.': 'Ron Harper',
  'Danuel House Jr.': 'Danuel House',
  'Kevin Knox II': 'Kevin Knox',
  'Reggie Bullock Jr.': 'Reggie Bullock',
  'Trey Murphy III': 'Trey Murphy',
  'A.J. Green': 'AJ Green',
  'AJ Lawson': 'A.J. Lawson',
  'David Duke Jr.': 'David Duke',
  'Brandon Boston Jr.': 'Brandon Boston',
  'Ricky Council IV': 'Ricky Council',
  'R.J. Hampton': 'RJ Hampton',
  'Scotty Pippen Jr.': 'Scotty Pippen',
}

export const teamNameMapper = {
  'NYK': 'NY',
  'GSW': 'GS',
  'PHX': 'PHO',
  'SAS': 'SA',
  'NOP': 'NO',
}